/**
 * Pixel sprites authored as string matrices — no binary assets.
 * Chars map to palette keys: S skin, R robe, A accent, D dark, W white.
 * A fighter sprite = shared pose body (16×24) + look overlay (head rows
 * 0–7: beard/wig/accessory) recolored by the roster palette.
 */

export type Palette = { skin: string; robe: string; accent: string; dark?: string };

const CHAR_MAP: Record<string, keyof Required<Palette> | null> = {
  '.': null,
  S: 'skin',
  R: 'robe',
  A: 'accent',
  D: 'dark',
  W: 'accent', // white detail → accent by default
};

export const SPRITE_W = 16;
export const SPRITE_H = 24;
/** Head/overlay region replaced per philosopher. */
export const OVERLAY_ROWS = 8;

export type PoseName =
  | 'idle' | 'idle2'
  | 'walk' | 'walk2'
  | 'crouch' | 'jump'
  | 'lp' | 'hp' | 'lk' | 'hk' | 'special'
  | 'block' | 'blockstun' | 'hitstun'
  | 'ko' | 'win';

/** Shared bodies. Rows 0–7 get replaced by the look overlay. */
export const POSES: Record<PoseName, string[]> = {
  idle: [
    '.......S........',
    '......SSS.......',
    '......SSS.......',
    '.......S........',
    '.....RRRRR......',
    '....RRRRRRR.....',
    '...SRRRRRRRS....',
    '...SRRRRRRRS....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '....AAA.AAA.....',
    '................',
    '................',
  ],
  idle2: [
    '.......S........',
    '......SSS.......',
    '......SSS.......',
    '.......S........',
    '.....RRRRR......',
    '....RRRRRRR.....',
    '...SRRRRRRRS....',
    '...SRRRRRRRS....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '....AAA.AAA.....',
    '................',
    '................',
  ],
  walk: [
    '.......S........',
    '......SSS.......',
    '......SSS.......',
    '.......S........',
    '.....RRRRR......',
    '....RRRRRRR.....',
    '...SRRRRRRRS....',
    '...SRRRRRRRS....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '.....RRRRR......',
    '....RRRRRRR.....',
    '....RRR.RR......',
    '....RR..RR......',
    '....RR...RR.....',
    '...RR.....RR....',
    '...RR.....RR....',
    '...RR.....RR....',
    '...RR......RR...',
    '...RR......RR...',
    '..AAA......AAA..',
    '................',
    '................',
  ],
  walk2: [
    '.......S........',
    '......SSS.......',
    '......SSS.......',
    '.......S........',
    '.....RRRRR......',
    '....RRRRRRR.....',
    '...SRRRRRRRS....',
    '...SRRRRRRRS....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '.....RRRRR......',
    '.....RRRRR......',
    '......RRR.RR....',
    '......RR..RR....',
    '......RR...RR...',
    '......RR....RR..',
    '......RR.....RR.',
    '.....RR......RR.',
    '.....RR.........',
    '.....RR.........',
    '....AAA.........',
    '................',
    '................',
  ],
  crouch: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.......S........',
    '......SSS.......',
    '......SSS.......',
    '.......S........',
    '.....RRRRR......',
    '....RRRRRRR.....',
    '...SRRRRRRRS....',
    '...SRRRRRRRS....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '...RRRRRRRRR....',
    '...RR.RRR.RR....',
    '...RR.RRR.RR....',
    '...RR.....RR....',
    '...RR.....RR....',
    '...RR.....RR....',
    '..AAA.....AAA...',
    '................',
  ],
  jump: [
    '.......S........',
    '......SSS.......',
    '......SSS.......',
    '.......S........',
    '.....RRRRR......',
    '....RRRRRRR.....',
    '...SRRRRRRRS....',
    '...SRRRRRRRS....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '.....RRRRR......',
    '.....RRRRR......',
    '....RRRRRRR.....',
    '....RR...RR.....',
    '....RR...RR.....',
    '...RR.....RR....',
    '...RR.....RR....',
    '..RR.......RR...',
    '..RR.......RR...',
    '................',
    '................',
    '................',
    '................',
  ],
  lp: [
    '.......S........',
    '......SSS.......',
    '......SSS.......',
    '.......S........',
    '.....RRRRR......',
    '....RRRRRRR.....',
    '...SRRRRRRRSSSS.',
    '...SRRRRRRR.....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '....AAA.AAA.....',
    '................',
    '................',
  ],
  hp: [
    '.......S........',
    '......SSS.......',
    '......SSS.......',
    '.......S........',
    '....RRRRRR......',
    '...RRRRRRRR.....',
    '..SRRRRRRRRSSSS.',
    '..SRRRRRRR......',
    '...RRRRRRR......',
    '...RRRRRRR......',
    '...RRRRRRR......',
    '....RRRRRR......',
    '....RRRRRR......',
    '....RRRRRR......',
    '....RRRRRR......',
    '....RRRRRR......',
    '....RR..RR......',
    '....RR..RR......',
    '...RR....RR.....',
    '...RR....RR.....',
    '...RR....RR.....',
    '..AAA....AAA....',
    '................',
    '................',
  ],
  lk: [
    '.......S........',
    '......SSS.......',
    '......SSS.......',
    '.......S........',
    '.....RRRRR......',
    '....RRRRRRR.....',
    '...SRRRRRRRS....',
    '...SRRRRRRRS....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RR.........',
    '.....RR.........',
    '.....RR.........',
    '.....RRR........',
    '......RRRRRRR...',
    '.........AAAAAA.',
    '................',
    '................',
  ],
  hk: [
    '.......S........',
    '......SSS.......',
    '......SSS.......',
    '.......S........',
    '.....RRRRR......',
    '....RRRRRRR.....',
    '...SRRRRRRRS....',
    '...SRRRRRRRS....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRRR.....',
    '.....RRR.RRRR...',
    '.....RR....RRR..',
    '.....RR.....RRR.',
    '.....RR......RRR',
    '.....RR.........',
    '.....RR.........',
    '.....RR.........',
    '....AAA.........',
    '................',
    '................',
  ],
  special: [
    '.......S........',
    '......SSS.......',
    '......SSS.......',
    '.......S........',
    '..S..RRRRR..S...',
    '...SRRRRRRRS....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '....AAA.AAA.....',
    '................',
    '................',
  ],
  block: [
    '.......S........',
    '......SSS.......',
    '......SSS.......',
    '.......S........',
    '.....RRRRR......',
    '....RRRRRRR.....',
    '....SRRRSRR.....',
    '....SRSRSR......',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '....AAA.AAA.....',
    '................',
    '................',
  ],
  blockstun: [
    '.......S........',
    '......SSS.......',
    '......SSS.......',
    '.......S........',
    '.....RRRRR......',
    '....RRRRRRR.....',
    '....SRRRSRR.....',
    '....SRSRSR......',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '....AAA.AAA.....',
    '................',
    '................',
  ],
  hitstun: [
    '........S.......',
    '.......SSS......',
    '.......SSS......',
    '........S.......',
    '......RRRRR.....',
    '.....RRRRRRR....',
    '....SRRRRRRRS...',
    '....SRRRRRRRS...',
    '.....RRRRRRR....',
    '.....RRRRRRR....',
    '.....RRRRRRR....',
    '......RRRRR.....',
    '......RRRRR.....',
    '......RRRRR.....',
    '......RRRRR.....',
    '......RRRRR.....',
    '......RR.RR.....',
    '......RR.RR.....',
    '.....RR..RR.....',
    '.....RR..RR.....',
    '.....RR..RR.....',
    '....AAA..AAA....',
    '................',
    '................',
  ],
  ko: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.SSSRRRRRRRRRRR.',
    '.RRRRRRRRRRRRRA.',
    '..SSSRRRRRRRRRA.',
    '................',
    '................',
  ],
  win: [
    '..S....S....S...',
    '..S...SSS...S...',
    '..S...SSS...S...',
    '.......S........',
    '.....RRRRR......',
    '....RRRRRRR.....',
    '...SRRRRRRRS....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '....RRRRRRR.....',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RRRRR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '.....RR.RR......',
    '....AAA.AAA.....',
    '................',
    '................',
  ],
};

/** Per-philosopher head overlays (rows 0–7). Keyed by roster `look`. */
export const LOOKS: Record<string, string[]> = {
  'bald-beard': [ // Sócrates
    '................',
    '.....DDDDD......',
    '....DSSSSSD.....',
    '....DSDSSDD.....',
    '....DSSSSSD.....',
    '....DDDDDD......',
    '.....DSSSD......',
    '......DDD.......',
  ],
  'beard-noble': [ // Platón
    '....AAAA........',
    '...DSSSSSD......',
    '...DSSSSSD......',
    '...DSDSSDD......',
    '...DSSSSSD......',
    '....DDDDDD......',
    '.....DSDD.......',
    '......DDD.......',
  ],
  'scroll-beard': [ // Aristóteles
    '.....DDDDD......',
    '....DSSSSSD.....',
    '....DSDSSDD.....',
    '....DSSSSSD.....',
    '....DDDDDDD.....',
    '.....DDDD.......',
    '......DDD.......',
    '................',
  ],
  'mystic-hood': [ // Plotino
    '.....RRRRR......',
    '....RSSSSSR.....',
    '....RSSSSSR.....',
    '....RSDSSDR.....',
    '....RSSSSSR.....',
    '.....RSSSR......',
    '......DDD.......',
    '................',
  ],
  'wig-prussian': [ // Kant
    '....WWWWWW......',
    '...WSSSSSSW.....',
    '...WSDSSSDW.....',
    '...WSSSSSSW.....',
    '....WSSSSW......',
    '.....WSSW.......',
    '......WWW.......',
    '................',
  ],
  'hair-flat': [ // Hegel
    '....DDDDDD......',
    '...DSSSSSSD.....',
    '...DSDSSSDD.....',
    '...DSSSSSSD.....',
    '....DSSSSD......',
    '.....DSSD.......',
    '......DDD.......',
    '................',
  ],
  'moustache-hammer': [ // Nietzsche
    '....DDDDDD......',
    '...DSSSSSSD.....',
    '...DSDSSSDD.....',
    '...DSSSSSSD.....',
    '...DDDDDDDD.....',
    '....DSSSSD......',
    '......DDD.......',
    '................',
  ],
  'suit-stern': [ // Heidegger
    '.....DDDD.......',
    '....DSSSSSD.....',
    '....DSDSSDD.....',
    '....DSSSSSD.....',
    '.....DSSSD......',
    '......DDD.......',
    '................',
    '................',
  ],
  'tie-cigar': [ // Lacan
    '....DDDDDD......',
    '...DSSSSSSD.....',
    '...DSDSSSDD.....',
    '...DSSSSSSD.....',
    '....DSSSSD......',
    '.....DSDD.......',
    '......DDD.......',
    '................',
  ],
};

export function composeSprite(pose: PoseName, look: string): string[] {
  const body = POSES[pose];
  const head = LOOKS[look] ?? LOOKS['bald-beard']!;
  return [...head.slice(0, OVERLAY_ROWS), ...body.slice(OVERLAY_ROWS)];
}

/** Rasterize a sprite matrix into an RGBA pixel buffer (scaled ×1). */
export function rasterize(rows: string[], palette: Palette): Uint8ClampedArray<ArrayBuffer> {
  const data = new Uint8ClampedArray(SPRITE_W * SPRITE_H * 4);
  const colors = {
    skin: hex(palette.skin),
    robe: hex(palette.robe),
    accent: hex(palette.accent),
    dark: hex(palette.dark ?? '#1a1420'),
  };
  for (let y = 0; y < Math.min(rows.length, SPRITE_H); y++) {
    const row = rows[y]!;
    for (let x = 0; x < Math.min(row.length, SPRITE_W); x++) {
      const key = CHAR_MAP[row[x]!];
      if (!key) continue;
      const [r, g, b] = colors[key];
      const i = (y * SPRITE_W + x) * 4;
      data[i] = r; data[i + 1] = g; data[i + 2] = b; data[i + 3] = 255;
    }
  }
  return data;
}

function hex(c: string): [number, number, number] {
  return [parseInt(c.slice(1, 3), 16), parseInt(c.slice(3, 5), 16), parseInt(c.slice(5, 7), 16)];
}
